-- AlterTable
ALTER TABLE `Material` MODIFY `dataAtualizacao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Usuario` MODIFY `dataAtualizacao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
