version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecosystem
      MYSQL_USER: admin
      MYSQL_PASSWORD: ecosystem
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./backup:/backup
    command: --default-authentication-plugin=mysql_native_password
