import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 14,
        borderStyle: 'solid',
        //borderWidth: 1,
        borderColor: '#000000ff',
        borderRadius: 8,
        alignSelf: 'center',
    },
    boxTop: {
        width: '90%',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
        borderRadius: 8,
        //backgroundColor: '#cbd6d6ff',
        padding: 16,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    titleSuportText: {
        fontSize: 12.9,
        textAlign: 'center',
        marginTop: 8,
        color: '#4a4a4aff',
    },
    boxMiddle: {
        width: '90%',
        justifyContent: 'flex-start',
        gap: 16,
        alignItems: 'stretch',
        marginBottom: 16,
        backgroundColor: '#ffffffff',
        boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
        borderRadius: 8,
        paddingTop: 24,
        paddingBottom: 24,
        paddingLeft: 12,
        paddingRight: 12,
    },
    boxPassword: {

    },
    input: {
        height: 49,
        width: 334,
        borderRadius: 8,
        borderColor: '#000000ff',
        borderWidth: 1,
    },
    boxBottom: {
        width: '90%',
        alignItems: 'center',
        justifyContent: 'center',
        //backgroundColor: 'gray',
        borderRadius: 8,
        padding: 16,
        marginTop: 16,
    },
    buttonEntrar: {
        alignItems: 'center',
        justifyContent: 'center',
        height: 49,
        width: 334,
        borderRadius: 8,
        backgroundColor: '#2163EB',
    },
    textButtonEntrar: {
        color: '#ffffff',
    },
    buttonCadastrar: {
        alignItems: 'center',
        justifyContent: 'center',
        height: 49,
        width: 334,
        borderRadius: 8,
        borderColor: '#2163EB',
        borderWidth: 1,
        marginTop: 8,
    },
    textButtonCadastrar: {
        color: '#2163EB',
    },
});
